//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KorgEX800Editor {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KorgEX800Editor.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korg EX-800 Voice Editor.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occured when trying to initialize the MIDI device:.
        /// </summary>
        internal static string DialogTextFatalInitError {
            get {
                return ResourceManager.GetString("DialogTextFatalInitError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occured when trying to initialize the MIDI input device:.
        /// </summary>
        internal static string DialogTextFatalInitInputError {
            get {
                return ResourceManager.GetString("DialogTextFatalInitInputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occured when trying to initialize the MIDI output device:.
        /// </summary>
        internal static string DialogTextFatalInitOutputError {
            get {
                return ResourceManager.GetString("DialogTextFatalInitOutputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following error occurred:.
        /// </summary>
        internal static string DialogTextGenericErrorOccurred {
            get {
                return ResourceManager.GetString("DialogTextGenericErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Korg EX-800 Voice Editor was written by Robert McMurray.
        ///   (www.robertmcmurray.com)
        ///
        ///Special thanks to Leslie Sanford for the C# MIDI Toolkit.
        ///   (www.lesliesanford.com).
        /// </summary>
        internal static string DialogTextHelpAbout {
            get {
                return ResourceManager.GetString("DialogTextHelpAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sysex data received was not the correct length.
        ///
        ///Make sure that no other MIDI devices are transmitting..
        /// </summary>
        internal static string DialogTextIncorrectSysexDataSize {
            get {
                return ResourceManager.GetString("DialogTextIncorrectSysexDataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file that you selected is not the correct size.
        ///
        ///Please check the file and try again..
        /// </summary>
        internal static string DialogTextIncorrectSysexFileSize {
            get {
                return ResourceManager.GetString("DialogTextIncorrectSysexFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following MIDI error occurred:.
        /// </summary>
        internal static string DialogTextMidiErrorOccurred {
            get {
                return ResourceManager.GetString("DialogTextMidiErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MIDI data was not received within the allotted time.
        ///
        ///Check your settings and MIDI connections then try again..
        /// </summary>
        internal static string DialogTextMidiTimeoutError {
            get {
                return ResourceManager.GetString("DialogTextMidiTimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MIDI Input devices are available.
        ///
        ///You will not be able to receive MIDI messages..
        /// </summary>
        internal static string DialogTextNoInputDevices {
            get {
                return ResourceManager.GetString("DialogTextNoInputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No MIDI output devices are available.
        ///
        ///You will not be able to send MIDI messages..
        /// </summary>
        internal static string DialogTextNoOutputDevices {
            get {
                return ResourceManager.GetString("DialogTextNoOutputDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File.
        /// </summary>
        internal static string DialogTextOpenFile {
            get {
                return ResourceManager.GetString("DialogTextOpenFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        internal static string DialogTextSaveFile {
            get {
                return ResourceManager.GetString("DialogTextSaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to syx.
        /// </summary>
        internal static string DialogTextSysexExtension {
            get {
                return ResourceManager.GetString("DialogTextSysexExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SysEx files|*.syx|All files|*.*.
        /// </summary>
        internal static string DialogTextSysexFilter {
            get {
                return ResourceManager.GetString("DialogTextSysexFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have unsaved changes.
        ///
        ///Do you want to save your changes before continuing?.
        /// </summary>
        internal static string DialogTextUnsavedChanges {
            get {
                return ResourceManager.GetString("DialogTextUnsavedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;About.
        /// </summary>
        internal static string MenuTextAbout {
            get {
                return ResourceManager.GetString("MenuTextAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Empty Voices.
        /// </summary>
        internal static string MenuTextEmptyVoices {
            get {
                return ResourceManager.GetString("MenuTextEmptyVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E&amp;xit.
        /// </summary>
        internal static string MenuTextExit {
            get {
                return ResourceManager.GetString("MenuTextExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;File.
        /// </summary>
        internal static string MenuTextFile {
            get {
                return ResourceManager.GetString("MenuTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Help.
        /// </summary>
        internal static string MenuTextHelp {
            get {
                return ResourceManager.GetString("MenuTextHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Input Device.
        /// </summary>
        internal static string MenuTextInputDevice {
            get {
                return ResourceManager.GetString("MenuTextInputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;MIDI.
        /// </summary>
        internal static string MenuTextMIDI {
            get {
                return ResourceManager.GetString("MenuTextMIDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;New.
        /// </summary>
        internal static string MenuTextNew {
            get {
                return ResourceManager.GetString("MenuTextNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Open.
        /// </summary>
        internal static string MenuTextOpen {
            get {
                return ResourceManager.GetString("MenuTextOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Options.
        /// </summary>
        internal static string MenuTextOptions {
            get {
                return ResourceManager.GetString("MenuTextOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Output Device.
        /// </summary>
        internal static string MenuTextOutputDevice {
            get {
                return ResourceManager.GetString("MenuTextOutputDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Random Voices.
        /// </summary>
        internal static string MenuTextRandomVoices {
            get {
                return ResourceManager.GetString("MenuTextRandomVoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Request Bank.
        /// </summary>
        internal static string MenuTextRequestBank {
            get {
                return ResourceManager.GetString("MenuTextRequestBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Save.
        /// </summary>
        internal static string MenuTextSave {
            get {
                return ResourceManager.GetString("MenuTextSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Send Bank.
        /// </summary>
        internal static string MenuTextSendBank {
            get {
                return ResourceManager.GetString("MenuTextSendBank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attack.
        /// </summary>
        internal static string UiTextAttack {
            get {
                return ResourceManager.GetString("UiTextAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Break.
        /// </summary>
        internal static string UiTextBreak {
            get {
                return ResourceManager.GetString("UiTextBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chorus.
        /// </summary>
        internal static string UiTextChorus {
            get {
                return ResourceManager.GetString("UiTextChorus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitally Controlled Oscillator 1.
        /// </summary>
        internal static string UiTextDCO1 {
            get {
                return ResourceManager.GetString("UiTextDCO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCO 1 Envelope Map.
        /// </summary>
        internal static string UiTextDCO1EnvelopeMap {
            get {
                return ResourceManager.GetString("UiTextDCO1EnvelopeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digitally Controlled Oscillator 2.
        /// </summary>
        internal static string UiTextDCO2 {
            get {
                return ResourceManager.GetString("UiTextDCO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCO 2 Envelope Map.
        /// </summary>
        internal static string UiTextDCO2EnvelopeMap {
            get {
                return ResourceManager.GetString("UiTextDCO2EnvelopeMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The controls for DCO 2 are enabled while the DCO mode is set to &apos;Double&apos;..
        /// </summary>
        internal static string UiTextDCOModeDouble {
            get {
                return ResourceManager.GetString("UiTextDCOModeDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCO Mode.
        /// </summary>
        internal static string UiTextDCOModeLabel {
            get {
                return ResourceManager.GetString("UiTextDCOModeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note: The controls for DCO 2 are disabled while the DCO mode is set to &apos;Whole&apos;..
        /// </summary>
        internal static string UiTextDCOModeWhole {
            get {
                return ResourceManager.GetString("UiTextDCOModeWhole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decay.
        /// </summary>
        internal static string UiTextDecay {
            get {
                return ResourceManager.GetString("UiTextDecay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detune.
        /// </summary>
        internal static string UiTextDetune {
            get {
                return ResourceManager.GetString("UiTextDetune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double.
        /// </summary>
        internal static string UiTextDouble {
            get {
                return ResourceManager.GetString("UiTextDouble", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string UiTextDown {
            get {
                return ResourceManager.GetString("UiTextDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string UiTextFull {
            get {
                return ResourceManager.GetString("UiTextFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half.
        /// </summary>
        internal static string UiTextHalf {
            get {
                return ResourceManager.GetString("UiTextHalf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16&apos;.
        /// </summary>
        internal static string UiTextHarmonic16 {
            get {
                return ResourceManager.GetString("UiTextHarmonic16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2&apos;.
        /// </summary>
        internal static string UiTextHarmonic2 {
            get {
                return ResourceManager.GetString("UiTextHarmonic2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4&apos;.
        /// </summary>
        internal static string UiTextHarmonic4 {
            get {
                return ResourceManager.GetString("UiTextHarmonic4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8&apos;.
        /// </summary>
        internal static string UiTextHarmonic8 {
            get {
                return ResourceManager.GetString("UiTextHarmonic8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Harmonics.
        /// </summary>
        internal static string UiTextHarmonics {
            get {
                return ResourceManager.GetString("UiTextHarmonics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string UiTextHigh {
            get {
                return ResourceManager.GetString("UiTextHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval.
        /// </summary>
        internal static string UiTextInterval {
            get {
                return ResourceManager.GetString("UiTextInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KBD T..
        /// </summary>
        internal static string UiTextKBDTrack {
            get {
                return ResourceManager.GetString("UiTextKBDTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string UiTextLevel {
            get {
                return ResourceManager.GetString("UiTextLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string UiTextLow {
            get {
                return ResourceManager.GetString("UiTextLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modulation Generator.
        /// </summary>
        internal static string UiTextMG {
            get {
                return ResourceManager.GetString("UiTextMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCO.
        /// </summary>
        internal static string UiTextMGDCO {
            get {
                return ResourceManager.GetString("UiTextMGDCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delay.
        /// </summary>
        internal static string UiTextMGDelay {
            get {
                return ResourceManager.GetString("UiTextMGDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freq..
        /// </summary>
        internal static string UiTextMGFrequency {
            get {
                return ResourceManager.GetString("UiTextMGFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VCF.
        /// </summary>
        internal static string UiTextMGVCF {
            get {
                return ResourceManager.GetString("UiTextMGVCF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mid.
        /// </summary>
        internal static string UiTextMid {
            get {
                return ResourceManager.GetString("UiTextMid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi.
        /// </summary>
        internal static string UiTextMulti {
            get {
                return ResourceManager.GetString("UiTextMulti", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noise.
        /// </summary>
        internal static string UiTextNoise {
            get {
                return ResourceManager.GetString("UiTextNoise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Octave.
        /// </summary>
        internal static string UiTextOctave {
            get {
                return ResourceManager.GetString("UiTextOctave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string UiTextOff {
            get {
                return ResourceManager.GetString("UiTextOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string UiTextOn {
            get {
                return ResourceManager.GetString("UiTextOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polarity.
        /// </summary>
        internal static string UiTextPolarity {
            get {
                return ResourceManager.GetString("UiTextPolarity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release.
        /// </summary>
        internal static string UiTextRelease {
            get {
                return ResourceManager.GetString("UiTextRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sawtooth.
        /// </summary>
        internal static string UiTextSawtooth {
            get {
                return ResourceManager.GetString("UiTextSawtooth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single.
        /// </summary>
        internal static string UiTextSingle {
            get {
                return ResourceManager.GetString("UiTextSingle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope.
        /// </summary>
        internal static string UiTextSlope {
            get {
                return ResourceManager.GetString("UiTextSlope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Squarewave.
        /// </summary>
        internal static string UiTextSquarewave {
            get {
                return ResourceManager.GetString("UiTextSquarewave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sustain.
        /// </summary>
        internal static string UiTextSustain {
            get {
                return ResourceManager.GetString("UiTextSustain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger.
        /// </summary>
        internal static string UiTextTrigger {
            get {
                return ResourceManager.GetString("UiTextTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string UiTextUp {
            get {
                return ResourceManager.GetString("UiTextUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltage Controlled Filter (VCF) and MG.
        /// </summary>
        internal static string UiTextVCFandMG {
            get {
                return ResourceManager.GetString("UiTextVCFandMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cutoff.
        /// </summary>
        internal static string UiTextVCFCutoff {
            get {
                return ResourceManager.GetString("UiTextVCFCutoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EG Int..
        /// </summary>
        internal static string UiTextVCFEGIntensity {
            get {
                return ResourceManager.GetString("UiTextVCFEGIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reson..
        /// </summary>
        internal static string UiTextVCFResonance {
            get {
                return ResourceManager.GetString("UiTextVCFResonance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voice.
        /// </summary>
        internal static string UiTextVoice {
            get {
                return ResourceManager.GetString("UiTextVoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waveform.
        /// </summary>
        internal static string UiTextWaveform {
            get {
                return ResourceManager.GetString("UiTextWaveform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole.
        /// </summary>
        internal static string UiTextWhole {
            get {
                return ResourceManager.GetString("UiTextWhole", resourceCulture);
            }
        }
    }
}
